version: "3.9"

services:
  api:
    build: .
    container_name: trading_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - pg

  pg:
    image: postgres:16
    container_name: trading_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-trading_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: