"""Add backtest_history table

Revision ID: 0004
Revises: 0003
Create Date: 2025-10-21 12:55:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=False),
        sa.Column("strategy_params", sa.JSON(), nullable=False),
        sa.Column("start_date", sa.String(length=50), nullable=True),
        sa.Column("end_date", sa.String(length=50), nullable=True),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("monte_carlo_runs", sa.Integer(), nullable=False),
        sa.Column("monte_carlo_method", sa.String(length=50), nullable=True),
        sa.Column("sample_fraction", sa.Float(), nullable=True),
        sa.Column("gaussian_scale", sa.Float(), nullable=True),
        sa.Column("datasets_used", sa.JSON(), nullable=True),
        sa.Column("price_type", sa.String(length=20), nullable=False),
        sa.Column("total_return", sa.Float(), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("total_trades", sa.Integer(), nullable=True),
        sa.Column("execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_history_id"), "backtest_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_backtest_history_user_id"),
        "backtest_history",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backtest_history_user_id"), table_name="backtest_history")
    op.drop_index(op.f("ix_backtest_history_id"), table_name="backtest_history")
    op.drop_table("backtest_history")
    # ### end Alembic commands ###
